### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by hemangshah** [thePsguy/ButtonProgressBar-iOS#3]
Hi @thePsguy, thanks for the cool library. I am having an issue with the last released source.

I believe it's the right time to update it for the latest Swift?

**Argument of '#selector' refers to instance method 'animateIndeterminate(sender:)' that is not exposed to Objective-C**

<img width="1104" alt="screen shot 2018-02-08 at 10 39 55 am" src="https://user-images.githubusercontent.com/3313412/35956539-7f61b7dc-0cbc-11e8-8608-f965b162bee3.png">

**Comment by thePsguy** [comment]
Hey @hemagshah,

Indeed. I'll be fixing this and the other issue in a few days. If you find anything else, feel free to create an issue.

Thanks!

**Comment by hemangshah** [comment]
Thanks for the quick response. @thePsguy, looking forward to seeing/making a better ButtonProgressBar for iOS!

**Comment by thePsguy** [comment]
Hey @hemangshah, Version 1.0.1 has been pushed and fixes this issue. You should be able to update to it by running `pod update`.
