### ISSUE TITLE
No storyboard support?

### ISSUE THREAD

**Issue by hemangshah** [thePsguy/ButtonProgressBar-iOS#4]
<img width="1096" alt="screen shot 2018-02-08 at 10 45 01 am" src="https://user-images.githubusercontent.com/3313412/35956660-259a116c-0cbd-11e8-9ccb-c662adfea0aa.png">

**Comment by thePsguy** [comment]
Hey @hemangshah, Version 1.0.1 adds support for storyboard initialization of the button as well. Note that the time period, target, and other actions still have to be added in code like they usually are for a normal UIButton.
